### PR TITLE
Add indexes on land.events and Update Ruby

### PR DESCRIPTION
**Pull request by rcbm**
This Pull Request:
* Updates Ruby from 2.6.6. to 2.7.4
* Updates PostgreSQL CircleCI image from 11.4 to 13.4
* Adds indexes to some `created_at` and `pageview_id ` on land.events

### CODE REVIEW

**Comment by rcbm** [comment]
[add created_at, pageview_id indexes on land.events](https://trello.com/c/bAJ2javq/3760-add-createdat-pageviewid-indexes-on-landevents)

**Comment by rcbm** [comment]
Once this is approved and merged I will create PRs for ADR and Beyond

**Review by ashzagorski — APPROVED** [review]
Looks good!

**Comment by ashzagorski** [comment]
@rcbm I will just merge this one in, is that alright?

**Comment by rcbm** [comment]
> 

Perfect, thank you!

**Pull request merged**
